collections:
  projects:
    output: true
  writings:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "base"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project-page"
  - scope:
      path: ""
      type: "writings"
    values:
      layout: "base writing-page"