collections:
  projects:
    output: true
  others:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project-page"
  - scope:
      path: ""
      type: "others"
    values:
      layout: "other-page"