collections:
  projects:
    output: true
  writings:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "base"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project-page"
      styles: "project-page"
      base-backlink: \projects.html
  - scope:
      path: ""
      type: "writings"
    values:
      layout: "writing-page"
      styles: "writing-page"
      base-backlink: \writings.html